apiVersion: v1
kind: Pod
metadata:
  name: configmap-env-pod
  namespace: configmap-testing
spec:
  containers:
    - name: configmap-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: singlevalue-map